//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoStep.Web.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptRunnerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptRunnerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoStep.Web.Scripts.ScriptRunnerMessages", typeof(ScriptRunnerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert the result of {0}.{1} to the expected {2}..
        /// </summary>
        internal static string CouldNotConvertFunctionResult {
            get {
                return ResourceManager.GetString("CouldNotConvertFunctionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert the result of {0} to the expected {1}..
        /// </summary>
        internal static string CouldNotConvertModuleResult {
            get {
                return ResourceManager.GetString("CouldNotConvertModuleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load requested script module {0}. Looked in: {1}.
        /// </summary>
        internal static string CouldNotLoadModule {
            get {
                return ResourceManager.GetString("CouldNotLoadModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} module does not export a default function. A function name should be supplied..
        /// </summary>
        internal static string DefaultModuleFunctionNotFound {
            get {
                return ResourceManager.GetString("DefaultModuleFunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while invoking the {0}.{1} method; &apos;{2}&apos;..
        /// </summary>
        internal static string ErrorInvokingFunctionScript {
            get {
                return ResourceManager.GetString("ErrorInvokingFunctionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while invoking the {0} method; &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorInvokingModuleScript {
            get {
                return ResourceManager.GetString("ErrorInvokingModuleScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred loading the {0} module; &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorLoadingModule {
            get {
                return ResourceManager.GetString("ErrorLoadingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function {0} was found within the {1} module. Is it exported?.
        /// </summary>
        internal static string FunctionNotFound {
            get {
                return ResourceManager.GetString("FunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking Script {0}.{1}..
        /// </summary>
        internal static string InvokingFunctionScript {
            get {
                return ResourceManager.GetString("InvokingFunctionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking Script {0}..
        /// </summary>
        internal static string InvokingModuleScript {
            get {
                return ResourceManager.GetString("InvokingModuleScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module {0} not loaded. Load Required..
        /// </summary>
        internal static string ModuleNotLoaded {
            get {
                return ResourceManager.GetString("ModuleNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No script providers are available..
        /// </summary>
        internal static string NoScriptProvidersAvailable {
            get {
                return ResourceManager.GetString("NoScriptProvidersAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect the {0} module after loading it..
        /// </summary>
        internal static string UnableToDetectedLoadedModule {
            get {
                return ResourceManager.GetString("UnableToDetectedLoadedModule", resourceCulture);
            }
        }
    }
}
