name: AutoStep Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Fetch tags for GitVersion
      run: git fetch --tags
      
    - name: Fetch master for GitVersion
      if: github.ref != 'refs/heads/master'
      run: git branch --create-reflog master origin/master
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
      
    - name: GitVersion
      id: gitversion  # step id used as reference for output values
      uses: roryprimrose/rungitversion@v1.0.0
     
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Run unit tests
      run: dotnet test --configuration Release --no-build

    - name: Restore Tools
      run: dotnet tool restore

    - name: Install Chromium
      run: |
        sudo apt-get install libxss1 libappindicator1 libindicator7
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome*.deb

    - name: Launch Test App (background)
      run: dotnet test-apps/Basic/bin/Release/netcoreapp3.1/Basic.dll &

    - name: Run AutoStep Tests
      run: dotnet autostep run -d interactions

    - name: Pack
      run:  dotnet pack ./src/AutoStep.Web/AutoStep.Web.csproj --no-build -o artifacts -c Release --version-suffix  ${{ steps.gitversion.outputs.PreReleaseTag }}
            
    - name: Push
      run: dotnet nuget push 'artifacts/*' -n true -s https://f.feedz.io/autostep/ci/nuget/index.json -k ${{ secrets.FEEDZ_IO_KEY }}